on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - 'dev/v.0.1.0-beta-release'
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Build Status

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Build
        run: make 
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: builds/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: "This is my release text"